//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yak.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResults {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResults() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yak.Tests.Resources.TestResults", typeof(TestResults).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: SET PIN LeftEyeRed TO ON
        ///INFO: SET PIN LeftEyeGreen TO ON
        ///INFO: SET PIN LeftEyeBlue TO OFF
        ///INFO: SET PIN RightEyeRed TO ON
        ///INFO: SET PIN RightEyeGreen TO ON
        ///INFO: SET PIN RightEyeBlue TO OFF
        ///.
        /// </summary>
        internal static string EyesAmber {
            get {
                return ResourceManager.GetString("EyesAmber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: SET PIN LeftEyeRed TO OFF
        ///INFO: SET PIN LeftEyeGreen TO OFF
        ///INFO: SET PIN LeftEyeBlue TO ON
        ///INFO: SET PIN RightEyeRed TO OFF
        ///INFO: SET PIN RightEyeGreen TO OFF
        ///INFO: SET PIN RightEyeBlue TO ON
        ///.
        /// </summary>
        internal static string EyesBlue {
            get {
                return ResourceManager.GetString("EyesBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: SET PIN LeftEyeRed TO OFF
        ///INFO: SET PIN LeftEyeGreen TO ON
        ///INFO: SET PIN LeftEyeBlue TO OFF
        ///INFO: SET PIN RightEyeRed TO OFF
        ///INFO: SET PIN RightEyeGreen TO ON
        ///INFO: SET PIN RightEyeBlue TO OFF
        ///.
        /// </summary>
        internal static string EyesGreen {
            get {
                return ResourceManager.GetString("EyesGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: SET PIN LeftEyeRed TO OFF
        ///INFO: SET PIN LeftEyeGreen TO OFF
        ///INFO: SET PIN LeftEyeBlue TO OFF
        ///INFO: SET PIN RightEyeRed TO OFF
        ///INFO: SET PIN RightEyeGreen TO OFF
        ///INFO: SET PIN RightEyeBlue TO OFF
        ///.
        /// </summary>
        internal static string EyesOff {
            get {
                return ResourceManager.GetString("EyesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: SET PIN LeftEyeRed TO ON
        ///INFO: SET PIN LeftEyeGreen TO OFF
        ///INFO: SET PIN LeftEyeBlue TO OFF
        ///INFO: SET PIN RightEyeRed TO ON
        ///INFO: SET PIN RightEyeGreen TO OFF
        ///INFO: SET PIN RightEyeBlue TO OFF
        ///.
        /// </summary>
        internal static string EyesRed {
            get {
                return ResourceManager.GetString("EyesRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: SET PIN RifleRed TO OFF
        ///INFO: SET PIN RifleGreen TO OFF
        ///INFO: SET PIN RifleBlue TO OFF
        ///.
        /// </summary>
        internal static string RifleOff {
            get {
                return ResourceManager.GetString("RifleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO: SET PIN RifleRed TO ON
        ///INFO: SET PIN RifleGreen TO OFF
        ///INFO: SET PIN RifleBlue TO OFF
        ///.
        /// </summary>
        internal static string RifleRed {
            get {
                return ResourceManager.GetString("RifleRed", resourceCulture);
            }
        }
    }
}
